# Generated by Django 5.1.7 on 2025-04-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datos_copeinca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('caldero_1', models.BooleanField()),
                ('caldero_2', models.BooleanField()),
                ('caldero_3', models.BooleanField()),
                ('caldero_4', models.BooleanField()),
                ('caldero_5', models.BooleanField()),
                ('caldero_6', models.BooleanField()),
                ('caldero_7', models.BooleanField()),
                ('caldero_8', models.BooleanField()),
                ('energia', models.FloatField()),
                ('velocidad', models.FloatField()),
                ('liquido', models.FloatField()),
            ],
        ),
    ]
